name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clear gh-pages branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin gh-pages
        git checkout gh-pages
        git rm -r *
        git commit -m "Clean old files"
        git push origin gh-pages


    - name: Checkout main branch again
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Install Python dependencies
      run: pip install git+https://www.github.com/hbldh/hitherdither

    - name: Process Images
      run: python utils/dither_images.py --directory content/
      env:
        PYTHON_VERSION: '3.8'

    - name: Build
      run: hugo --config config/config.toml --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        keep_files: false
        clean: true
